### ISSUE TITLE
有意向换工作环境吗 杭州TOP互联网电商平台

### ISSUE THREAD

**Issue by wangxiaojs** [peterchenhdu/webbf#12]
hi 同学：
    你是前后端都做吗？ 我们这边招前端开发工程师，React技术栈，有意向换工作环境吗？
我们是杭州TOP互联网电商平台

**Comment by peterchenhdu** [comment]
好巧，正好离职了，可惜我主要是后端的，前端很久没弄了，哈哈哈

**Comment by wangxiaojs** [comment]
可以继续做前端哈 我们也希望有后端经验的前端同学

2017-08-08 19:58 GMT+08:00 风一样的码农 <notifications@github.com>:
