### ISSUE TITLE
运行npm还要装nodejs吧

### ISSUE THREAD

**Issue by howepeng** [peterchenhdu/webbf#3]
readme 中的【输入npm run build命令构建即可】是不是要用nodejs去执行啊。
eclipse应该不能吧？

**Comment by peterchenhdu** [comment]
对啊，npm肯定要装的

**Comment by peterchenhdu** [comment]
对啊，npm肯定要装的

**Comment by howepeng** [comment]
那是不是直接用nodejs比较好。用java web还要装npm怪怪的。

**Comment by peterchenhdu** [comment]
也可以啊；
但是有时候后端就是需要用java，然后前端又喜欢用react，然后前端的模块包用npm管理。
